logging:
  level:
    guru:
      springframework: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_prod_user
    password: sfg_prod_user
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
